MYSQL_DB_HOST = "127.0.0.1"
MYSQL_DB_PORT = "13306"
MYSQL_DB_USER = "root"
MYSQL_DB_PASSWORD = "root"

DATE_FORMAT = "%Y-%m-%d"

TABLE_EVENTS = "events"
TABLE_SPEC_METRICS = "spec_metrics"
TABLE_SPEC_DIMENSIONS = "spec_dimensions"

TEST_BASE_URL = "http://127.0.0.1:8000"

ERROR_MESSAGE_INVALID_BODY_CONTENTS_NOT_EXIST_FROM = "INVALID_BODY_CONTENTS: from 값이 존재하지 않음"
ERROR_MESSAGE_INVALID_BODY_CONTENTS_INVALID_VALUE_FROM = "INVALID_BODY_CONTENTS: from 값이 올바르지 않음"
ERROR_MESSAGE_INVALID_BODY_CONTENTS_NOT_EXIST_TO = "INVALID_BODY_CONTENTS: to 값이 존재하지 않음"
ERROR_MESSAGE_INVALID_BODY_CONTENTS_INVALID_VALUE_TO = "INVALID_BODY_CONTENTS: to 값이 올바르지 않음"
ERROR_MESSAGE_INVALID_BODY_CONTENTS_INVALID_VALUE_FROM_TO = "INVALID_BODY_CONTENTS: from, to 값이 올바르지 않음"

ERROR_MESSAGE_INVALID_BODY_CONTENTS_NOT_EXIST_METRICS = "INVALID_BODY_CONTENTS: metrics 값이 존재하지 않음"
ERROR_MESSAGE_INVALID_BODY_CONTENTS_INVALID_VALUE_METRICS = "INVALID_BODY_CONTENTS: metrics 값이 올바르지 않음"
ERROR_MESSAGE_INVALID_BODY_CONTENTS_INVALID_VALUE_DIMENSIONS = "INVALID_BODY_CONTENTS: dimensions 값이 올바르지 않음"

ERROR_MESSAGE_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
